from __future__ import annotations

import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from app.models.schemas import AnalysisResponse


class ForensicReportGenerator:
    def generate(self, response: AnalysisResponse, output_dir: str = "./reports") -> str:
        os.makedirs(output_dir, exist_ok=True)
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        out_path = os.path.join(output_dir, f"forensic_report_{ts}.pdf")

        c = canvas.Canvas(out_path, pagesize=A4)
        w, h = A4
        y = h - 20 * mm

        def line(text: str, step_mm: float = 7.0) -> None:
            nonlocal y
            c.drawString(15 * mm, y, text)
            y -= step_mm * mm
            if y < 20 * mm:
                c.showPage()
                y = h - 20 * mm

        c.setFont("Helvetica-Bold", 14)
        line("Digital Forensic Analysis Report", 9)

        c.setFont("Helvetica", 10)
        line(f"Analyzed At: {response.analyzed_at.isoformat()}")
        line(f"Evidence SHA-256: {response.evidence_hash_sha256}")
        line(f"Media Type: {response.media_type}")
        line(f"Case ID: {response.case_id or 'N/A'}", 9)

        c.setFont("Helvetica-Bold", 12)
        line("Final Assessment", 8)
        c.setFont("Helvetica", 10)
        line(f"Authenticity Score: {response.fusion.authenticity_score}%")
        line(f"Manipulation Likelihood: {response.fusion.manipulation_likelihood}%")
        line(f"Classification: {response.fusion.classification}")
        line(f"Explanation: {response.fusion.explanation}", 9)

        c.setFont("Helvetica-Bold", 12)
        line("Module Results", 8)
        c.setFont("Helvetica", 10)

        for module in response.module_results:
            line(f"- {module.module}: confidence={module.confidence:.2f}")
            if not module.indicators:
                line("  no significant indicators")
            for ind in module.indicators:
                line(f"  [{ind.severity}] {ind.name} ({ind.score:.2f})")
                line(f"  detail: {ind.detail}")

        line("Generated by forensic pipeline; verify model validation records before legal filing.", 7)

        c.save()
        return out_path
